### ISSUE TITLE
TODO list up

### ISSUE THREAD

**Issue by shingonu** [Onther-Tech/zk-dex#45]
Vue:
- [ ] delete note helper
- [ ]  mapState
- [ ] pending data until server commits
- [ ] use standard button

**Comment by shingonu** [comment]
renew-vapp-with-zk-dex-service-server
-> reset to `1cdc526`
...
-> merge zk-dex-service-server

**Comment by shingonu** [comment]
server

- [ ] unlock check (front)
- [ ] multiple vk (how to use)
